src/app/budget_quiz/app/src/routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BudgetChapterController;
use App\Http\Controllers\Admin\BudgetStateChangeController;
use App\Http\Controllers\Admin\BudgetStateController;
use App\Http\Controllers\Admin\EducationController;
use App\Http\Controllers\Admin\PartyController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\AnswerController;
use App\Http\Controllers\QuizController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('index');

Route::controller(QuizController::class)->group(function() {
    Route::get('quiz', 'index')->name('quiz.index');
    Route::get('results/{quiz}', 'quizResults')->name('results.quiz');
    Route::get('results', 'results')->name('results');
});

Route::controller(LoginController::class)->group(function() {
    Route::post('admin/login', 'login');
    Route::get('admin/login', 'show')->name('admin.login');
    Route::get('admin/logout', 'logout')->name('admin.logout');
});

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
   Route::get('/', [AdminController::class, 'index'])->name('welcome');

   Route::resource('regions', RegionController::class)->except('show');

   Route::resource('parties', PartyController::class)->except('show');

   Route::resource('educations', EducationController::class)->except('show');

   Route::resource('budget_chapters', BudgetChapterController::class)->except('show');
   Route::resource('budget_chapters.budget_state', BudgetStateController::class)->except('index');

   Route::resource('questions', QuestionController::class);
   Route::resource('questions.answers', AnswerController::class)->except('index');
   Route::resource('questions.answers.budget_state_change', BudgetStateChangeController::class)->except('index');
});

src/app/budget_quiz/app/src/app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Represents quiz question
 *
 * @property $id
 * @property $created_at
 * @property $updated_at
 * @property $number
 * @property $title
 * @property $description
 */
class Question extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['number', 'title', 'description'];

    /**
     * Get all answers for this question
     */
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
}

src/app/budget_quiz/app/src/app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\QuestionRequest;
use App\Models\Question;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        return view('admin.questions.index', [
            'questions' => Question::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        return view('admin.questions.create-or-update', [
            "question" => new Question
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param QuestionRequest $request
     */
    public function store(QuestionRequest $request)
    {
        $validated = $request->validated();

        $question = new Question;

        $question->number = $validated['question_number'];
        $question->title = $validated['question_title'];
        $question->description = $validated['question_description'];

        $question->save();

        return redirect()->route('admin.questions.index')->with('success', 'Otázka ID '. $question->id .' byla přidána');
    }

    /**
     * Display the specified resource.
     *
     * @param Question $question
     */
    public function show(Question $question)
    {
        return view('admin.questions.show', [
            'question' => $question
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Question $question
     */
    public function edit(Question $question)
    {
        return view('admin.questions.create-or-update', [
            "question" => $question
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param QuestionRequest $request
     * @param Question $question
     */
    public function update(QuestionRequest $request, Question $question)
    {
        $validated = $request->validated();

        $question->number = $validated['question_number'];
        $question->title = $validated['question_title'];
        $question->description = $validated['question_description'];

        $question->save();

        return redirect()->route('admin.questions.show', $question)->with('success', 'Otázka byla upravena');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Question $question
     */
    public function destroy(Question $question)
    {
        $question->delete();

        return redirect()->route('admin.questions.index')->with('success', 'Otázka ID ' . $question->id . ' byla smazána');
    }
}

src/app/budget_quiz/app/src/resources/views/admin/questions/create-or-update.blade.php
<x-admin.layout>
    <x-slot:title>
        @if($question->exists)
            Upravit kapitolu státního rozpočtu ID {{ $question->id }}
        @else
            Přidat novou kapitolu státního rozpočtu
        @endif
    </x-slot:title>

    <form action="@if($question->exists) {{ route('admin.questions.update', $question)  }} @else {{ route('admin.questions.store') }} @endif" method="POST">
        @csrf
        @if($question->exists)
            @method('PATCH')
        @endif
        <div class="mb-3">
            <label for="question-number-input" class="form-label">Číslo otázky</label>
            <input type="number" name="question_number"
                   value="{{ old('question_number', $question->number) }}"
                   id="question-number-input"
                   @class(['form-control', 'is-invalid' => $errors->has('question_number')])
                   required>
            @error('question_number')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="question-title-input" class="form-label">Titulek</label>
            <input type="text" name="question_title"
                   value="{{ old('question_title', $question->title) }}"
                   id="question-title-input"
                   @class(['form-control', 'is-invalid' => $errors->has('question_title')])
                   maxlength="100" required>
            @error('question_title')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="question-description-input" class="form-label">Popis</label>
            <textarea name="question_description"
                      id="question-description-input"
                      @class(['form-control', 'is-invalid' => $errors->has('question_description')])
                      required>{{ old('question_description', $question->description) }}</textarea>
            @error('question_description')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">@if($question->exists) Upravit @else Přidat @endif</button>
    </form>
</x-admin.layout>

src/app/budget_quiz/app/src/resources/views/admin/questions/index.blade.php
<x-admin.layout>
    <x-slot:title>Otázky</x-slot:title>
    <x-slot:description>Zde jsou definované kvízové otázky</x-slot:description>

    <x-admin.button-add :href="route('admin.questions.create')" />

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Číslo</th>
                        <th>Titulek</th>
                        <th>Akce</th>
                    </tr>
                </thead>
                <tbody>
                @forelse ($questions as $question)
                    <tr>
                        <td>{{ $question->id }}</td>
                        <td>{{ $question->number }}</td>
                        <td>{{ $question->title }}</td>
                        <td class="actions-col">
                            <x-admin.button-icon-show :href="route('admin.questions.show', $question)" />
                            <x-admin.button-icon-edit :href="route('admin.questions.edit', $question)" />
                            <x-admin.button-icon-delete :href="route('admin.questions.destroy', $question)" />
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" class="text-center">
                            Žádná otázka nebyla nalezena. <a href="{{ route('admin.questions.create') }}">Přidat novou otázku</a>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
</x-admin.layout>

src/app/budget_quiz/app/src/resources/views/admin/questions/show.blade.php
<x-admin.layout>
    <x-slot:title>
       Otázka ID {{ $question->id }}
    </x-slot:title>

    <div class="row">
        <div class="col-md-6">
            <h4>Číslo otázky</h4>
            {{ $question->number }}

            <h4>Titulek</h4>
            {{ $question->title }}

            <h4>Popis</h4>
            {{ $question->description }}
        </div>
        <div class="col-md-6">
            <h2>Odpovědi</h2>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Titulek</th>
                            <th>Změna stavu rozpočtu</th>
                            <th>Akce</th>
                        </tr>
                    </thead>
                    <tbody>
                    @forelse($question->answers as $answer)
                        <tr>
                            <td>{{ $answer->id }}</td>
                            <td>{{ $answer->title }}</td>
                            <td>
                                @if(empty($answer->budgetStateChange))
                                    <a href="{{ route("admin.questions.answers.budget_state_change.create", [$question, $answer]) }}">Přidat změnu stavu rozpočtu</a>
                                @else
                                    <a href="{{ route("admin.questions.answers.budget_state_change.show", [$question, $answer, $answer->budgetStateChange]) }}">Zobrazit změnu stavu rozpočtu</a>
                                @endif
                            </td>
                            <td class="actions-col">
                                <x-admin.button-icon-show :href="route('admin.questions.answers.show', [$question, $answer])" />
                                <x-admin.button-icon-edit :href="route('admin.questions.answers.edit', [$question, $answer])" />
                                <x-admin.button-icon-delete :href="route('admin.questions.answers.destroy', [$question, $answer])" />
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" class="text-center">
                                Žádná odpověď nebyla nalezena. <a href="{{ route('admin.questions.answers.create', $question) }}">Přidat novou odpověď</a>
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>

            <x-admin.button-add :href="route('admin.questions.answers.create', $question)" />
        </div>
    </div>

    <div class="mt-3">
        <x-admin.button-edit :href="route('admin.questions.edit', $question)" />
        <x-admin.button-delete :href="route('admin.questions.destroy', $question)" />
        <x-admin.button-back :href="route('admin.questions.index')">Zpět na výpis otázek</x-admin.button-back>
    </div>
</x-admin.layout>