src/app/budget_quiz/app/src/routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BudgetChapterController;
use App\Http\Controllers\Admin\BudgetStateChangeController;
use App\Http\Controllers\Admin\BudgetStateController;
use App\Http\Controllers\Admin\EducationController;
use App\Http\Controllers\Admin\PartyController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\AnswerController;
use App\Http\Controllers\QuizController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('index');

Route::controller(QuizController::class)->group(function() {
    Route::get('quiz', 'index')->name('quiz.index');
    Route::get('results/{quiz}', 'quizResults')->name('results.quiz');
    Route::get('results', 'results')->name('results');
});

Route::controller(LoginController::class)->group(function() {
    Route::post('admin/login', 'login');
    Route::get('admin/login', 'show')->name('admin.login');
    Route::get('admin/logout', 'logout')->name('admin.logout');
});

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
   Route::get('/', [AdminController::class, 'index'])->name('welcome');

   Route::resource('regions', RegionController::class)->except('show');

   Route::resource('parties', PartyController::class)->except('show');

   Route::resource('educations', EducationController::class)->except('show');

   Route::resource('budget_chapters', BudgetChapterController::class)->except('show');
   Route::resource('budget_chapters.budget_state', BudgetStateController::class)->except('index');

   Route::resource('questions', QuestionController::class);
   Route::resource('questions.answers', AnswerController::class)->except('index');
   Route::resource('questions.answers.budget_state_change', BudgetStateChangeController::class)->except('index');
});

src/app/budget_quiz/app/src/app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Represents Answer entity from database
 *
 * @property $id
 * @property $created_at
 * @property $updated_at
 * @property $title
 * @property $description
 * @property $question_id
 */
class Answer extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description'];

    /**
     * Get the question that this answer belongs to
     */
    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    /**
     * Get the budget state change, that this answer makes
     */
    public function budgetStateChange()
    {
        return $this->hasOne(BudgetStateChange::class);
    }

    /**
     * Get all quizzes in which this answer is chosen
     */
    public function quizzes()
    {
        return $this->belongsToMany(Quiz::class, 'quiz_answers');
    }
}

src/app/budget_quiz/app/src/app/Http/Controllers/Admin/AnswerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AnswerRequest;
use App\Models\Answer;
use App\Models\Question;

class AnswerController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @param Question $question
     */
    public function create(Question $question)
    {
        return view('admin.answers.create-or-update', [
            'question' => $question,
            'answer'   => new Answer
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AnswerRequest $request
     * @param Question $question
     */
    public function store(AnswerRequest $request, Question $question)
    {
        $validated = $request->validated();

        $answer = new Answer;

        $answer->title = $validated['answer_title'];
        $answer->description = $validated['answer_description'];

        $question->answers()->save($answer);

        return redirect()->route('admin.questions.show', $question)->with('success', 'Odpověď byla přidána úspěšně');
    }

    /**
     * Display the specified resource.
     *
     * @param Question $question
     * @param Answer $answer
     */
    public function show(Question $question, Answer $answer)
    {
        return view('admin.answers.show', [
            'question' => $question,
            'answer' => $answer
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Question $question
     * @param Answer $answer
     */
    public function edit(Question $question, Answer $answer)
    {
        return view('admin.answers.create-or-update', [
            'question' => $question,
            'answer' => $answer
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AnswerRequest $request
     * @param Question $question
     * @param Answer $answer
     */
    public function update(AnswerRequest $request, Question $question, Answer $answer)
    {
        $validated = $request->validated();

        $answer->title = $validated['answer_title'];
        $answer->description = $validated['answer_description'];

        $question->answers()->save($answer);

        return redirect()->route('admin.questions.answers.show', [$question, $answer])->with('success', 'Odpověď byla upravena úspěšně');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Question $question
     * @param Answer $answer
     */
    public function destroy(Question $question, Answer $answer)
    {
        $answer->delete();

        return redirect()->route('admin.questions.show', $question)->with('success', 'Odpověď byla smazána');
    }
}

src/app/budget_quiz/app/src/resources/views/admin/answers/create-or-update.blade.php
<x-admin.layout>
    <x-slot:title>
        @if($answer->exists)
            Upravit odpověď ID {{ $answer->id }}
        @else
            Přidat odpověď
        @endif
    </x-slot:title>

    <x-slot:description>
        Pro otázku ID {{ $question->id }} (č. {{ $question->number }} – {{ $question->title }})
    </x-slot:description>

    <form action="@if($answer->exists) {{ route('admin.questions.answers.update', [$question, $answer])  }} @else {{ route('admin.questions.answers.store', $question) }} @endif" method="POST">
        @csrf
        @if($answer->exists)
            @method('PATCH')
        @endif

        <div class="mb-3">
            <label for="answer-title-input" class="form-label">Titulek</label>
            <input type="text" name="answer_title"
                   value="{{ old('answer_title', $answer->title) }}"
                   id="answer-title-input"
                   @class(['form-control', 'is-invalid' => $errors->has('answer_title')])
                   maxlength="100" required>
            @error('answer_title')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="answer-description-input" class="form-label">Popis</label>
            <textarea name="answer_description"
                      id="answer-description-input"
                      @class(['form-control', 'is-invalid' => $errors->has('answer_description')])
                      required>{{ old('answer_description', $answer->description) }}</textarea>
            @error('answer_description')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">@if($answer->exists) Upravit @else Přidat @endif</button>
    </form>
</x-admin.layout>

src/app/budget_quiz/app/src/resources/views/admin/answers/show.blade.php
<x-admin.layout>
    <x-slot:title>
        Odpověď ID {{ $answer->id }}
    </x-slot:title>

    <x-slot:description>
        Pro otázku ID {{ $question->id }} (č. {{ $question->number }} – {{ $question->title }})
    </x-slot:description>

    <h4>Titulek</h4>
    <div class="item-value mb-3">{{ $answer->title }}</div>

    <h4>Popis</h4>
    <div class="item-value mb-3">{{ $answer->description }}</div>

    <h4>Změna stavu rozpočtu</h4>
    <div class="item-value mb-3">
        @if(empty($answer->budgetStateChange))
            <a href="{{ route("admin.questions.answers.budget_state_change.create", [$question, $answer]) }}">Přidat změnu stavu rozpočtu</a>
        @else
            <a href="{{ route("admin.questions.answers.budget_state_change.show", [$question, $answer, $answer->budgetStateChange]) }}">Zobrazit změnu stavu rozpočtu</a>
        @endif
    </div>

    <div class="mt-3">
        <x-admin.button-edit :href="route('admin.questions.answers.edit', [$question, $answer])" />
        <x-admin.button-delete :href="route('admin.questions.answers.destroy', [$question, $answer])" />
        <x-admin.button-back :href="route('admin.questions.show', $question)">Zpět na otázku</x-admin.button-back>
    </div>
</x-admin.layout>