src/app/budget_quiz/app/src/routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BudgetChapterController;
use App\Http\Controllers\Admin\BudgetStateChangeController;
use App\Http\Controllers\Admin\BudgetStateController;
use App\Http\Controllers\Admin\EducationController;
use App\Http\Controllers\Admin\PartyController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\AnswerController;
use App\Http\Controllers\QuizController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('index');

Route::controller(QuizController::class)->group(function() {
    Route::get('quiz', 'index')->name('quiz.index');
    Route::get('results/{quiz}', 'quizResults')->name('results.quiz');
    Route::get('results', 'results')->name('results');
});

Route::controller(LoginController::class)->group(function() {
    Route::post('admin/login', 'login');
    Route::get('admin/login', 'show')->name('admin.login');
    Route::get('admin/logout', 'logout')->name('admin.logout');
});

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
   Route::get('/', [AdminController::class, 'index'])->name('welcome');

   Route::resource('regions', RegionController::class)->except('show');

   Route::resource('parties', PartyController::class)->except('show');

   Route::resource('educations', EducationController::class)->except('show');

   Route::resource('budget_chapters', BudgetChapterController::class)->except('show');
   Route::resource('budget_chapters.budget_state', BudgetStateController::class)->except('index');

   Route::resource('questions', QuestionController::class);
   Route::resource('questions.answers', AnswerController::class)->except('index');
   Route::resource('questions.answers.budget_state_change', BudgetStateChangeController::class)->except('index');
});

src/app/budget_quiz/app/src/app/Models/BudgetChapter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Represents budget chapter
 *
 * @property $id
 * @property $created_at
 * @property $updated_at
 * @property $number
 * @property $name
 */
class BudgetChapter extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['number', 'name'];

    /**
     * Get the initial budget state for this budget chapter
     */
    public function budgetState()
    {
        return $this->hasOne(BudgetState::class);
    }

    /**
     * Get all budget state changes that this budget chapter participates in
     */
    public function budgetStateChanges()
    {
        return $this->hasMany(BudgetStateChange::class);
    }
}

src/app/budget_quiz/app/src/app/Http/Controllers/Admin/BudgetChapterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\BudgetChapterRequest;
use App\Models\BudgetChapter;

class BudgetChapterController extends Controller
{
    /**
     * Display all budget chapters
     *
     */
    public function index()
    {
        return view('admin.budget_chapters.index', [
            "budgetChapters" => BudgetChapter::with('budgetState')->get()
        ]);
    }

    /**
     * Show the form for creating a new budget chapter
     *
     */
    public function create()
    {
        return view('admin.budget_chapters.create-or-update', ["budgetChapter" => new BudgetChapter]);
    }

    /**
     * Store new budget chapter
     *
     * @param BudgetChapterRequest $request
     */
    public function store(BudgetChapterRequest $request)
    {
        $validated = $request->validated();

        $budgetChapter = new BudgetChapter;

        $budgetChapter->number = $validated['budget_chapter_number'];
        $budgetChapter->name = $validated['budget_chapter_name'];

        $budgetChapter->save();

        return redirect()->route('admin.budget_chapters.index')->with('success', 'Kapitola rozpočtu číslo "'. $budgetChapter->number .'" byla přidána');
    }

    /**
     * Show the form for editing budget chapter
     *
     * @param BudgetChapter $budgetChapter
     */
    public function edit(BudgetChapter $budgetChapter)
    {
        return view('admin.budget_chapters.create-or-update', ["budgetChapter" => $budgetChapter]);
    }

    /**
     * Update budget chapter
     *
     * @param BudgetChapterRequest $request
     * @param BudgetChapter $budgetChapter
     */
    public function update(BudgetChapterRequest $request, BudgetChapter $budgetChapter)
    {
        $validated = $request->validated();

        $budgetChapter->number = $validated['budget_chapter_number'];
        $budgetChapter->name = $validated['budget_chapter_name'];

        $budgetChapter->save();

        return redirect()->route('admin.budget_chapters.index')->with('success', 'Kapitola rozpočtu číslo "'. $budgetChapter->number .'" byla upravena');
    }

    /**
     * Remove budget chapter
     *
     * @param BudgetChapter $budgetChapter
     */
    public function destroy(BudgetChapter $budgetChapter)
    {
        $budgetChapter->delete();

        return redirect()->route('admin.budget_chapters.index')->with('success', 'Kapitola rozpočtu číslo "' . $budgetChapter->number . '" byla smazána');
    }
}

src/app/budget_quiz/app/src/resources/views/admin/budget_chapters/create-or-update.blade.php
<x-admin.layout>
    <x-slot:title>
        @if($budgetChapter->exists)
            Upravit kapitolu státního rozpočtu ID {{ $budgetChapter->id }}
        @else
            Přidat novou kapitolu státního rozpočtu
        @endif
    </x-slot:title>

    <form action="@if($budgetChapter->exists) {{ route('admin.budget_chapters.update', $budgetChapter)  }} @else {{ route('admin.budget_chapters.store') }} @endif" method="POST">
        @csrf
        @if($budgetChapter->exists)
            @method('PATCH')
        @endif
        <div class="mb-3">
            <label for="budget-chapter-number-input" class="form-label">Číslo</label>
            <input type="number" name="budget_chapter_number"
                   value="{{ old('budget_chapter_number', $budgetChapter->number) }}"
                   id="budget-chapter-number-input"
                   @class(['form-control', 'is-invalid' => $errors->has('budget_chapter_number')])
                   required>
            @error('budget_chapter_number')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="budget-chapter-name-input" class="form-label">Název</label>
            <input type="text" name="budget_chapter_name"
                   value="{{ old('budget_chapter_name', $budgetChapter->name) }}"
                   id="budget-chapter-name-input"
                   @class(['form-control', 'is-invalid' => $errors->has('budget_chapter_name')])
                   maxlength="100" required>
            @error('budget_chapter_name')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">@if($budgetChapter->exists) Upravit @else Přidat @endif</button>
    </form>
</x-admin.layout>

src/app/budget_quiz/app/src/resources/views/admin/budget_chapters/index.blade.php
<x-admin.layout>
    <x-slot:title>Kapitoly státního rozpočtu</x-slot:title>
    <x-slot:description>Zde jsou definované kapitoly státního rozpočtu, ke kterým se může přiřadit počáteční stav státního rozpočtu</x-slot:description>

    <x-admin.button-add :href="route('admin.budget_chapters.create')" />

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Číslo</th>
                        <th>Název</th>
                        <th>Stav rozpočtu</th>
                        <th>Akce</th>
                    </tr>
                </thead>
                <tbody>
                @forelse ($budgetChapters as $budgetChapter)
                    <tr>
                        <td>{{ $budgetChapter->id }}</td>
                        <td>{{ $budgetChapter->number }}</td>
                        <td>{{ $budgetChapter->name }}</td>
                        <td>
                            @if(empty($budgetChapter->budgetState))
                                <a href="{{ route("admin.budget_chapters.budget_state.create", $budgetChapter) }}">Přidat stav rozpočtu</a>
                            @else
                                <a href="{{ route("admin.budget_chapters.budget_state.show", [$budgetChapter, $budgetChapter->budgetState]) }}">Zobrazit stav rozpočtu</a>
                            @endif
                        </td>
                        <td class="actions-col">
                            <x-admin.button-icon-edit :href="route('admin.budget_chapters.edit', $budgetChapter)" />
                            <x-admin.button-icon-delete :href="route('admin.budget_chapters.destroy', $budgetChapter)" />
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="text-center">
                            Žádná kapitola státního rozpočtu nebyla nalezena. <a href="{{ route('admin.budget_chapters.create') }}">Přidat novou kapitolu státního rozpočtu</a>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
</x-admin.layout>