src/app/budget_quiz/app/src/routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BudgetChapterController;
use App\Http\Controllers\Admin\BudgetStateChangeController;
use App\Http\Controllers\Admin\BudgetStateController;
use App\Http\Controllers\Admin\EducationController;
use App\Http\Controllers\Admin\PartyController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\AnswerController;
use App\Http\Controllers\QuizController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('index');

Route::controller(QuizController::class)->group(function() {
    Route::get('quiz', 'index')->name('quiz.index');
    Route::get('results/{quiz}', 'quizResults')->name('results.quiz');
    Route::get('results', 'results')->name('results');
});

Route::controller(LoginController::class)->group(function() {
    Route::post('admin/login', 'login');
    Route::get('admin/login', 'show')->name('admin.login');
    Route::get('admin/logout', 'logout')->name('admin.logout');
});

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
   Route::get('/', [AdminController::class, 'index'])->name('welcome');

   Route::resource('regions', RegionController::class)->except('show');

   Route::resource('parties', PartyController::class)->except('show');

   Route::resource('educations', EducationController::class)->except('show');

   Route::resource('budget_chapters', BudgetChapterController::class)->except('show');
   Route::resource('budget_chapters.budget_state', BudgetStateController::class)->except('index');

   Route::resource('questions', QuestionController::class);
   Route::resource('questions.answers', AnswerController::class)->except('index');
   Route::resource('questions.answers.budget_state_change', BudgetStateChangeController::class)->except('index');
});

src/app/budget_quiz/app/src/app/Models/BudgetState.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Represents initial budget state
 *
 * @property $id
 * @property $created_at
 * @property $updated_at
 * @property $income_first_year
 * @property $income_second_year
 * @property $income_third_year
 * @property $expense_first_year
 * @property $expense_second_year
 * @property $expense_third_year
 * @property $budget_chapter_id
 */
class BudgetState extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'income_first_year',
        'income_second_year',
        'income_third_year',
        'expense_first_year',
        'expense_second_year',
        'expense_third_year'
    ];

    /**
     * Get budget chapter to which this initial budget state belongs
     */
    public function budgetChapter()
    {
        return $this->belongsTo(BudgetChapter::class);
    }
}

src/app/budget_quiz/app/src/app/Http/Controllers/Admin/BudgetStateController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\BudgetStateRequest;
use App\Models\BudgetChapter;
use App\Models\BudgetState;

class BudgetStateController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     */
    public function create(BudgetChapter $budgetChapter)
    {
        if (!empty($budgetChapter->budgetState)) {
            return redirect()->route('admin.budget_chapters.index')->with('error', 'Kapitola rozpočtu ID ' . $budgetChapter->id . ' již má přiřazen stav rozpočtu');
        }

        return view('admin.budget_states.create-or-update', [
            'budgetChapter' => $budgetChapter,
            'budgetState' => new BudgetState
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BudgetStateRequest $request
     */
    public function store(BudgetStateRequest $request, BudgetChapter $budgetChapter)
    {
        if (!empty($budgetChapter->budgetState)) {
            return redirect()->route('admin.budget_chapters.index')->with('error', 'Kapitola rozpočtu ID ' . $budgetChapter->id . ' již má přiřazen stav rozpočtu');
        }

        $validated = $request->validated();
        $budgetState = new BudgetState;

        $budgetState->income_first_year = $validated['budget_state_income_first_year'];
        $budgetState->income_second_year = $validated['budget_state_income_second_year'];
        $budgetState->income_third_year = $validated['budget_state_income_third_year'];
        $budgetState->expense_first_year = $validated['budget_state_expense_first_year'];
        $budgetState->expense_second_year = $validated['budget_state_expense_second_year'];
        $budgetState->expense_third_year = $validated['budget_state_expense_third_year'];

        $budgetChapter->budgetState()->save($budgetState);

        return redirect()->route('admin.budget_chapters.index')->with('success', 'Stav rozpočtu byl vytvořen úspěšně');
    }

    /**
     * Display the specified resource.
     *
     * @param BudgetChapter $budgetChapter
     * @param BudgetState $budgetState
     */
    public function show(BudgetChapter $budgetChapter, BudgetState $budgetState)
    {
        return view('admin.budget_states.show', [
           'budgetChapter' => $budgetChapter,
           'budgetState' => $budgetState
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param BudgetChapter $budgetChapter
     * @param BudgetState $budgetState
     */
    public function edit(BudgetChapter $budgetChapter, BudgetState $budgetState)
    {
        return view('admin.budget_states.create-or-update', [
            'budgetChapter' => $budgetChapter,
            'budgetState' => $budgetState
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BudgetStateRequest $request
     * @param BudgetState $budgetState
     */
    public function update(BudgetStateRequest $request, BudgetChapter $budgetChapter, BudgetState $budgetState)
    {
        $validated = $request->validated();

        $budgetState->income_first_year = $validated['budget_state_income_first_year'];
        $budgetState->income_second_year = $validated['budget_state_income_second_year'];
        $budgetState->income_third_year = $validated['budget_state_income_third_year'];
        $budgetState->expense_first_year = $validated['budget_state_expense_first_year'];
        $budgetState->expense_second_year = $validated['budget_state_expense_second_year'];
        $budgetState->expense_third_year = $validated['budget_state_expense_third_year'];

        $budgetChapter->budgetState()->save($budgetState);

        return redirect()->route('admin.budget_chapters.budget_state.show', [$budgetChapter, $budgetState])->with('success', 'Stav rozpočtu byl aktualizován úspěšně');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param BudgetChapter $budgetChapter
     * @param BudgetState $budgetState
     */
    public function destroy(BudgetChapter $budgetChapter, BudgetState $budgetState)
    {
        $budgetState->delete();

        return redirect()->route('admin.budget_chapters.index')->with('success', 'Stav rozpočtu byl smazán');
    }
}

src/app/budget_quiz/app/src/resources/views/admin/budget_states/create-or-update.blade.php
<x-admin.layout>
    <x-slot:title>
        @if($budgetState->exists)
            Upravit počáteční stav státního rozpočtu ID {{ $budgetState->id }}
        @else
            Přidat počáteční stav státního rozpočtu
        @endif
    </x-slot:title>

    <x-slot:description>
        Pro kapitolu státního rozpočtu ID {{ $budgetChapter->id }} ({{ $budgetChapter->number }} – {{ $budgetChapter->name }})
    </x-slot:description>

    <form action="@if($budgetState->exists) {{ route('admin.budget_chapters.budget_state.update', [$budgetChapter, $budgetState])  }} @else {{ route('admin.budget_chapters.budget_state.store', $budgetChapter) }} @endif" method="POST">
        @csrf
        @if($budgetState->exists)
            @method('PATCH')
        @endif

        <div class="row">
            <div class="col-md-6">
                <h2>Příjmy</h2>

                <label for="budget-state-income-first-year-input" class="form-label">{{ config('app.first_year') }}</label>
                <div class="input-group mb-3">
                    <input type="number" name="budget_state_income_first_year"
                           value="{{ old('budget_state_income_first_year', $budgetState->income_first_year) }}"
                           id="budget-state-income-first-year-input"
                           @class(['form-control', 'is-invalid' => $errors->has('budget_state_income_first_year')])
                           min="0" required>
                    <div class="input-group-append">
                        <span class="input-group-text">Kč</span>
                    </div>
                    @error('budget_state_income_first_year')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <label for="budget-state-income-second-year-input" class="form-label">{{ config('app.second_year') }}</label>
                <div class="input-group mb-3">
                    <input type="number" name="budget_state_income_second_year"
                           value="{{ old('budget_state_income_second_year', $budgetState->income_second_year) }}"
                           id="budget-state-income-second-year-input"
                           @class(['form-control', 'is-invalid' => $errors->has('budget_state_income_second_year')])
                           min="0" required>
                    <div class="input-group-append">
                        <span class="input-group-text">Kč</span>
                    </div>
                    @error('budget_state_income_second_year')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <label for="budget-state-income-third-year-input" class="form-label">{{ config('app.third_year') }}</label>
                <div class="input-group mb-3">
                    <input type="number" name="budget_state_income_third_year"
                           value="{{ old('budget_state_income_third_year', $budgetState->income_third_year) }}"
                           id="budget-state-income-third-year-input"
                           @class(['form-control', 'is-invalid' => $errors->has('budget_state_income_third_year')])
                           min="0" required>
                    <div class="input-group-append">
                        <span class="input-group-text">Kč</span>
                    </div>
                    @error('budget_state_income_third_year')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
            </div>
            <div class="col-md-6">
                <h2>Výdaje</h2>

                <label for="budget-state-expense-first-year-input" class="form-label">{{ config('app.first_year') }}</label>
                <div class="input-group mb-3">
                    <input type="number" name="budget_state_expense_first_year"
                           value="{{ old('budget_state_expense_first_year', $budgetState->expense_first_year) }}"
                           id="budget-state-expense-first-year-input"
                           @class(['form-control', 'is-invalid' => $errors->has('budget_state_expense_first_year')])
                           min="0" required>
                    <div class="input-group-append">
                        <span class="input-group-text">Kč</span>
                    </div>
                    @error('budget_state_expense_first_year')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <label for="budget-state-expense-second-year-input" class="form-label">{{ config('app.second_year') }}</label>
                <div class="input-group mb-3">
                    <input type="number" name="budget_state_expense_second_year"
                           value="{{ old('budget_state_expense_second_year', $budgetState->expense_second_year) }}"
                           id="budget-state-expense-second-year-input"
                           @class(['form-control', 'is-invalid' => $errors->has('budget_state_expense_second_year')])
                           min="0" required>
                    <div class="input-group-append">
                        <span class="input-group-text">Kč</span>
                    </div>
                    @error('budget_state_expense_second_year')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <label for="budget-state-expense-third-year-input" class="form-label">{{ config('app.third_year') }}</label>
                <div class="input-group mb-3">
                    <input type="number" name="budget_state_expense_third_year"
                           value="{{ old('budget_state_expense_third_year', $budgetState->expense_third_year) }}"
                           id="budget-state-expense-third-year-input"
                           @class(['form-control', 'is-invalid' => $errors->has('budget_state_expense_third_year')])
                           min="0" required>
                    <div class="input-group-append">
                        <span class="input-group-text">Kč</span>
                    </div>
                    @error('budget_state_expense_third_year')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">@if($budgetState->exists) Upravit @else Přidat @endif</button>
    </form>
</x-admin.layout>

src/app/budget_quiz/app/src/resources/views/admin/budget_states/show.blade.php
<x-admin.layout>
    <x-slot:title>
        Stav státního rozpočtu ID {{ $budgetState->id }}
    </x-slot:title>

    <x-slot:description>
        Pro kapitolu státního rozpočtu ID {{ $budgetChapter->id }} ({{ $budgetChapter->number }} – {{ $budgetChapter->name }})
    </x-slot:description>

    <div class="row">
        <div class="col-md-6">
            <h2>Příjmy</h2>

            <h4>{{ config('app.first_year') }}</h4>
            <div class="item-value mb-3">{{ number_format($budgetState->income_first_year, 0, null, ' ') }}&nbsp;Kč</div>

            <h4>{{ config('app.second_year') }}</h4>
            <div class="item-value mb-3">{{ number_format($budgetState->income_second_year, 0, null, ' ') }}&nbsp;Kč</div>

            <h4>{{ config('app.first_year') }}</h4>
            <div class="item-value mb-3">{{ number_format($budgetState->income_third_year, 0, null, ' ') }}&nbsp;Kč</div>
        </div>

        <div class="col-md-6">
            <h2>Výdaje</h2>

            <h4>{{ config('app.first_year') }}</h4>
            <div class="item-value mb-3">{{ number_format($budgetState->expense_first_year, 0, null, ' ') }}&nbsp;Kč</div>

            <h4>{{ config('app.second_year') }}</h4>
            <div class="item-value mb-3">{{ number_format($budgetState->expense_second_year, 0, null, ' ') }}&nbsp;Kč</div>

            <h4>{{ config('app.first_year') }}</h4>
            <div class="item-value mb-3">{{ number_format($budgetState->expense_third_year, 0, null, ' ') }}&nbsp;Kč</div>

        </div>
    </div>

    <div class="mt-3">
        <x-admin.button-edit :href="route('admin.budget_chapters.budget_state.edit', [$budgetChapter, $budgetState])" />
        <x-admin.button-delete :href="route('admin.budget_chapters.budget_state.destroy', [$budgetChapter, $budgetState])" />
        <x-admin.button-back :href="route('admin.budget_chapters.index')">Zpět na výpis kapitol</x-admin.button-back>
    </div>
</x-admin.layout>